directory: ~/music
library: ~/.config/beets/library.db

# move cleaned music instead of copy
import:
        move: yes

paths:
        default: $albumartist/$album ($year)/$track - $title
        comp: Compilations/$album ($year)/$track - $title

plugins: copyartifacts fetchart info scrub

fetchart:
        enforce_ratio: yes
        minwidth: 500
